[package]
name = "bot"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow = "1.0.104"
dotenvy = "0.15.7"
rusqlite = { version = "0.31", features = ["bundled"] }
teloxide = { version = "0.17.0", features = ["macros"] }
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "signal"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
wallet-core = { version = "0.1.0", path = "../wallet-core" }
